version: '3.7'
services:
  nginx:
    ports:
      - "3000:80"
    networks:
      - elastic
  api-geteaway:
    build:
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - ./api-geteaway:/app
      - /app/node_modules
      - api-logs:/app/logs
    networks:
      - elastic
  auth:
    build:
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - ./auth:/app
      - /app/node_modules
      - auth-logs:/app/logs
    networks:
      - elastic
  billing:
    build:
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - ./billing:/app
      - /app/node_modules
      - billing-logs:/app/logs
    networks:
      - elastic

networks:
  elastic:
    name: elastic

volumes:
  api-logs:
  auth-logs:
  billing-logs: