version: '3.7'
services:
  nginx:
    ports:
      - "3000:80"
  #  ----- nest apps -----
  api-geteaway:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./api-geteaway:/app
      - /app/node_modules
      - api-logs:/app/logs
  auth:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./auth:/app
      - /app/node_modules
      - auth-logs:/app/logs
  billing:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./billing:/app
      - /app/node_modules
      - billing-logs:/app/logs
