version: '3.7'
services:
  nginx:
    ports:
      - "80:80"
  #  ----- nest apps -----
  api-geteaway:
    build:
      args:
        NODE_ENV: production
    volumes:
      - api-logs:/app/logs
  auth:
    build:
      args:
        NODE_ENV: production
    volumes:
      - auth-logs:/app/logs
  billing:
    build:
      args:
        NODE_ENV: production
    volumes:
      - billing-logs:/app/logs