version: '3.7'
services:
  nginx:
    ports:
      - "80:80"
  #  ----- nest apps -----
  api-geteaway:
    build:
      args:
        NODE_ENV: production
  auth:
    build:
      args:
        NODE_ENV: production
  billing:
    build:
      args:
        NODE_ENV: production