global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    metrics_path: /metrics
    scrape_interval: 5s
  
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['es-node-01:9200']